[project]
name = "bot"
version = "0.1.0"
description = "Expense Tracker Bot"
authors = [
    {name = "enclay",email = "enclayff@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot",
    "python-dotenv",
    "openai",
    "requests (>=2.32.3,<3.0.0)"
]

[tool.poetry.scripts]
start = "bot.main:main"
migrate = "scripts.migrate:apply_migrations"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
